// src/client-react/src/App.js
import React, { useEffect, useState, useCallback } from 'react'
import './App.css';
import { makeStyles } from '@material-ui/core/styles';
import { AppBar, Toolbar, Typography, Button, LinearProgress } from '@material-ui/core'
import { Link } from 'react-router-dom'
import Dropdown from './components/Dropdown'
import LoginDialog from './views/dialogs/LoginDialog'
import SprintDialog from './views/dialogs/SprintDialog'
import RouteConfig from './RouteConfig'
import AlertBox from './views/content/AlertBox'
import state from './state'
import actions from './actions'
import loginService from './services/loginService'
import signalRService from './services/signalRService'

const useStyles = makeStyles((theme) => ({  
  login: {
    marginRight: theme.spacing(4),
    marginLeft: theme.spacing(2),
  },
  dropdown: {
    marginRight: theme.spacing(2),
    minWidth: 200,
  },
  dropdownButton: {
    marginRight: theme.spacing(2),
  },
  appBar: {
    position: 'relative',
  },
  layout: {
    width: 'auto',
    padding: theme.spacing(4),
  },
  title: {
    flexGrow: 1,
  },
}));

function App() {
  const classes = useStyles();

  const [sprints, setSprints] = useState([]);
  const [currentSprint, setCurrentSprint] = useState(state.sprints.current);
  const [isFetching, setIsFetching] = useState(false);
  const [user, setUser] = useState(null);

  const onSprintChange = useCallback((value) => {
    state.sprints.current = value;
    setCurrentSprint(value);
  }, [])

  useEffect(() => {
    signalRService.initialize();

    if(loginService.isLoggedIn()) {
      loginService.getUser(true).then(u => {
        state.user.value.next(u);
      });
    } else {
      loginService.logout(true);
    }
    

    if(state.classifications.values.value.length == 0) {
      actions.classifications.fetch();
    }

    if(state.sprints.values.value.length == 0) {
      actions.sprints.fetch().then(() => {
        if(state.sprints.values.value.length != 0) {
          const firstSprint = state.sprints.values.value[0].id;
          onSprintChange(firstSprint);
          return actions.tasks.fetch(state.sprints.current);
        }
      });
    } else {
      const firstSprint = state.sprints.values.value[0].id;
      onSprintChange(firstSprint);
    }
  }, [onSprintChange]);

  useEffect(() => {
    actions.tasks.fetch(currentSprint);
  }, [currentSprint]);

  useEffect(() => {
    const sub = state.sprints.values.subscribe(x => {
      setSprints(x);
    })

    return () => sub.unsubscribe();
  }, []);

  useEffect(() => {
    const sub = state.isFetching.subscribe(x => {
      setIsFetching(x);
    })

    return () => sub.unsubscribe();
  }, [])

  useEffect(() => {
    const sub = state.user.value.subscribe(x => {
        setUser(x);
    });

    return () => sub.unsubscribe();
  }, []);

  

  const onSprintSave = useCallback((sprint) => {
    actions.sprints.addSprint(sprint).then(() => {
      return actions.sprints.fetch();
    })
  }, [])

  const onLogin = useCallback((login) => {
    loginService.login({
      Username: login.username,
      Password: login.password
    })
  }, [])

  const onLogout = useCallback(() => {
    loginService.logout();
  }, [])

  return (
    <div>
      <AppBar className={classes.appBar} color="transparent">
        <Toolbar>
          <LoginDialog className={classes.login} onLogin={onLogin} onLogout={onLogout} />
          <Typography variant="h6" className={classes.title}>
            <Link to="/"><Button>Dashboard</Button></Link>
            <Link to="/stats"><Button>Statistics</Button></Link>
          </Typography>
          <Dropdown className={classes.dropdown} label="Sprint" defaultValue={currentSprint} data={sprints} onDropdownChange={onSprintChange} />
          <SprintDialog className={classes.dropdownButton} disabled={user == null || user.Role.Name != 'Admin'} onSave={onSprintSave} />
        </Toolbar>
      </AppBar>
      { isFetching ? <LinearProgress /> : null }
      <main className={classes.layout}>
        <RouteConfig />
        <AlertBox />
      </main>
    </div>
  );
}

export default App;

// src/client-vue/src/App.vue
<template>
  <v-app id="inspire">
    <v-app-bar
      app
      color="white"
      flat>
      <v-container class="py-0 fill-height">
        <LoginDialog @on-login="onLogin" @on-logout="onLogout" />

        <v-btn
          v-for="link in links"
          :key="link.name"
          text
          @click="$router.push({ name: link.name }).catch(_ => _)">
          <v-icon left>{{ link.icon }}</v-icon>
          {{ link.name }}
        </v-btn>

        <v-spacer></v-spacer>

        <v-responsive max-width="260">
          <v-select
            :items="state.sprints.values"
            :item-text="'name'"
            :item-value="'id'"
            @change="onSprintChange"
            :value="state.sprints.current"
            label="Sprint"
            prepend-icon="mdi-run"
            hide-details
            single-line
            class="ma-2"
          ></v-select>
        </v-responsive>

        <SprintDialog :disabled="!state.user.isAdmin" @on-save="onSprintSave" />
      </v-container>
    </v-app-bar>
  
    <v-main class="grey lighten-3">
      <v-progress-linear indeterminate color="cyan" v-show="state.isFetching" />
      <v-container>
        <router-view />
        <AlertBox />
      </v-container>
    </v-main>
  </v-app>
</template>

<script>

import SprintDialog from '@/views/dialogs/SprintDialog'
import LoginDialog from '@/views/dialogs/LoginDialog'
import AlertBox from '@/views/content/AlertBox'
import state from '@/state'
import SignalRService from '@/services/signalRService'
import LoginService from '@/services/loginService'


export default {
  name: 'App',

  components: {
    SprintDialog,
    LoginDialog,
    AlertBox
  },

  data: () => ({
    state,
    links: [
      { name: 'Dashboard', icon: 'mdi-view-dashboard-variant'},
      { name: 'Statistics', icon: 'mdi-chart-areaspline'},
    ],
  }),

  methods: {
    onSprintChange(value) {
      state.sprints.setCurrentSprint(value);
      state.tasks.fetch(state.sprints.current);
    },
    onSprintSave($event) {
      state.sprints.addSprint($event.sprint).then(() => {
        return state.sprints.fetch();
      });
    },
    onLogin($event) {
      LoginService.login({
        Username: $event.login.username,
        Password: $event.login.password,
      })
    },
    onLogout() {
      LoginService.logout();
    },
  },

  created() {
    SignalRService.initialize();
    LoginService.getUser(true).then(u => {
      state.user.setUser(u);
    });


    if(state.classifications.values.length == 0) {
      state.classifications.fetch();
    }

    if(state.sprints.values.length == 0) {
      state.sprints.fetch().then(() => {
        if(state.sprints.values.length != 0) {
          state.sprints.setCurrentSprint(state.sprints.values[0].id);
          return state.tasks.fetch(state.sprints.current);
        }
      });
    } else {
      state.sprints.setCurrentSprint(state.sprints.values[0].id);
    }
  }
};
</script>


<style>
  html {
    overflow-y: auto !important;
  }
</style>
